source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
inhibit_all_warnings!

pod 'MZTimerLabel', '~>0.5.4'
pod 'JSKTimerView', '~>0.4.1'
pod 'RWBlurPopover', '~>3.1.0'
#pod 'ZCAnimatedLabel', '~>0.0.1'
pod 'EGOCache', '~>2.1.3'
pod 'RJBlurAlertView', '~>0.0.2'
pod 'OpenShare', '~>0.0.1'
#pod 'Google-Mobile-Ads-SDK', '~>7.4.1'
pod 'SCViewShaker', '~>1.0.2'
pod 'CircleProgressBar', '~>0.21'
pod 'VCTransitionsLibrary', '~>1.5.0'
#pod 'UIView+Shimmer', '~>1.0.0'
pod 'GTScrollNavigationBar', '~>0.2'
pod 'ARTransitionAnimator', :git => 'https://github.com/AugustRush/ARTransitionAnimator.git'
pod 'JGProgressHUD', '~>1.3'
pod 'UAAppReviewManager', '~>0.2.6'
pod 'FXBlurView', '~>1.6.4'
pod 'HUMSlider', '~>1.1.0'
#pod 'RZTransitions', '~>1.1.1'