source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
inhibit_all_warnings!

pod 'MZTimerLabel', '~>0.5.4'
pod 'JSKTimerView', '~>0.4.1'
pod 'RWBlurPopover', '~>3.1.0'
pod 'ZCAnimatedLabel', '~>0.0.1'
pod 'EGOCache', '~>2.1.3'
pod 'NuweScoreCharts', '~>1.0.0'
pod 'RJBlurAlertView', '~>0.0.2'
pod 'OpenShare', '~>0.0.1'
pod 'Google-Mobile-Ads-SDK', '~>7.4.1'
pod 'SCViewShaker', '~>1.0.2'
pod 'CircleProgressBar', '~>0.21'
pod 'VCTransitionsLibrary', '~>1.5.0'
pod 'UIView+Shimmer', '1.0.0'